name: Deploy to org environment on push to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Deploy-to-org-environment:
    runs-on: ubuntu-latest
    environment: growbiz3-dev-ed

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate with Salesforce
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username "${{ secrets.DEPLOYMENT_USER_NAME }}" \
            --jwt-key-file server.key \
            --client-id "${{ secrets.CONSUMER_KEY }}" \
            --instance-url "${{ vars.INSTANCE_URL }}" \
            --set-default
          rm server.key

      - name: Build, Test & Deploy
        uses: gfarb/sfdx-deploy@v1
        env:
          TARGET_USERNAME: ${{ secrets.DEPLOYMENT_USER_NAME }}
          SOURCE_PATH: force-app
          DESTRUCTIVE_CHANGES: destructive-changes  # if you have destructive changes
          TEST_LEVEL: RunLocalTests
          WAIT: 60