name: Deploy to org environment on push to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Deploy-to-org-environment:
    runs-on: ubuntu-latest
    environment: orgfarm-8bf35803e5-dev-ed

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate with Salesforce
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username "${{ secrets.DEPLOYMENT_USER_NAME }}" \
            --jwt-key-file server.key \
            --client-id "${{ secrets.CONSUMER_KEY }}" \
            --instance-url "${{ vars.INSTANCE_URL }}" \
            --set-default
          rm server.key

      - name: Convert and Deploy Source
        run: |
          # Convert source to metadata format
          sf project convert source -d mdapiout -r force-app
          
          # Deploy with test execution
          sf project deploy start \
            -d mdapiout \
            --target-org ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --test-level RunLocalTests \
            --wait 60
          
          # Check for and deploy destructive changes if they exist
          if [ -d "destructive-changes" ]; then
            if [ -f "destructive-changes/destructiveChangesPre.xml" ]; then
              sf project deploy start \
                -x destructive-changes/destructiveChangesPre.xml \
                --target-org ${{ secrets.DEPLOYMENT_USER_NAME }} \
                --test-level NoTestRun \
                --wait 60
            fi
            
            if [ -f "destructive-changes/destructiveChangesPost.xml" ]; then
              sf project deploy start \
                -x destructive-changes/destructiveChangesPost.xml \
                --target-org ${{ secrets.DEPLOYMENT_USER_NAME }} \
                --test-level NoTestRun \
                --wait 60
            fi
          fi